package com.noq.domain;

// Generated May 3, 2014 8:01:12 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Events generated by hbm2java
 */
@Entity
@Table(name = "events", catalog = "noqshows_test")
public class Events implements java.io.Serializable {

	private Integer eventid;
	private User user;
	private int eventcategory;
	private String eventtitle;
	private String eventlocation;
	private String eventtype;
	private String eventdetails;
	private String noofseats;
	private Date eventdate;
	private String eventimagepath;
	private String eventorganisernumber;
	private String eventorganisermailid;
	private Integer createdby;
	private Date createdtime;
	private Integer modifiedby;
	private Date modifiedtime;

	public Events() {
	}

	public Events(User user, int eventcategory, String eventtitle,
			String eventorganisernumber, String eventorganisermailid) {
		this.user = user;
		this.eventcategory = eventcategory;
		this.eventtitle = eventtitle;
		this.eventorganisernumber = eventorganisernumber;
		this.eventorganisermailid = eventorganisermailid;
	}

	public Events(User user, int eventcategory, String eventtitle,
			String eventlocation, String eventtype, String eventdetails,
			String noofseats, Date eventdate, String eventimagepath,
			String eventorganisernumber, String eventorganisermailid,
			Integer createdby, Date createdtime, Integer modifiedby,
			Date modifiedtime) {
		this.user = user;
		this.eventcategory = eventcategory;
		this.eventtitle = eventtitle;
		this.eventlocation = eventlocation;
		this.eventtype = eventtype;
		this.eventdetails = eventdetails;
		this.noofseats = noofseats;
		this.eventdate = eventdate;
		this.eventimagepath = eventimagepath;
		this.eventorganisernumber = eventorganisernumber;
		this.eventorganisermailid = eventorganisermailid;
		this.createdby = createdby;
		this.createdtime = createdtime;
		this.modifiedby = modifiedby;
		this.modifiedtime = modifiedtime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "eventid", unique = true, nullable = false)
	public Integer getEventid() {
		return this.eventid;
	}

	public void setEventid(Integer eventid) {
		this.eventid = eventid;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "eventaddedby", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "eventcategory", nullable = false)
	public int getEventcategory() {
		return this.eventcategory;
	}

	public void setEventcategory(int eventcategory) {
		this.eventcategory = eventcategory;
	}

	@Column(name = "eventtitle", nullable = false, length = 50)
	public String getEventtitle() {
		return this.eventtitle;
	}

	public void setEventtitle(String eventtitle) {
		this.eventtitle = eventtitle;
	}

	@Column(name = "eventlocation", length = 45)
	public String getEventlocation() {
		return this.eventlocation;
	}

	public void setEventlocation(String eventlocation) {
		this.eventlocation = eventlocation;
	}

	@Column(name = "eventtype", length = 45)
	public String getEventtype() {
		return this.eventtype;
	}

	public void setEventtype(String eventtype) {
		this.eventtype = eventtype;
	}

	@Column(name = "eventdetails", length = 455)
	public String getEventdetails() {
		return this.eventdetails;
	}

	public void setEventdetails(String eventdetails) {
		this.eventdetails = eventdetails;
	}

	@Column(name = "noofseats", length = 45)
	public String getNoofseats() {
		return this.noofseats;
	}

	public void setNoofseats(String noofseats) {
		this.noofseats = noofseats;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "eventdate", length = 0)
	public Date getEventdate() {
		return this.eventdate;
	}

	public void setEventdate(Date eventdate) {
		this.eventdate = eventdate;
	}

	@Column(name = "eventimagepath", length = 345)
	public String getEventimagepath() {
		return this.eventimagepath;
	}

	public void setEventimagepath(String eventimagepath) {
		this.eventimagepath = eventimagepath;
	}

	@Column(name = "eventorganisernumber", nullable = false, length = 12)
	public String getEventorganisernumber() {
		return this.eventorganisernumber;
	}

	public void setEventorganisernumber(String eventorganisernumber) {
		this.eventorganisernumber = eventorganisernumber;
	}

	@Column(name = "eventorganisermailid", nullable = false, length = 55)
	public String getEventorganisermailid() {
		return this.eventorganisermailid;
	}

	public void setEventorganisermailid(String eventorganisermailid) {
		this.eventorganisermailid = eventorganisermailid;
	}

	@Column(name = "createdby")
	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdtime", length = 0)
	public Date getCreatedtime() {
		return this.createdtime;
	}

	public void setCreatedtime(Date createdtime) {
		this.createdtime = createdtime;
	}

	@Column(name = "modifiedby")
	public Integer getModifiedby() {
		return this.modifiedby;
	}

	public void setModifiedby(Integer modifiedby) {
		this.modifiedby = modifiedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifiedtime", length = 0)
	public Date getModifiedtime() {
		return this.modifiedtime;
	}

	public void setModifiedtime(Date modifiedtime) {
		this.modifiedtime = modifiedtime;
	}

}
