package com.noq.domain;

// Generated May 3, 2014 8:01:12 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Eventregistration generated by hbm2java
 */
@Entity
@Table(name = "eventregistration", catalog = "noqshows_test")
public class Eventregistration implements java.io.Serializable {

	private int id;
	private String eventid;
	private String userid;
	private String attendeeName;
	private String attendeeAge;
	private String attendeeDob;
	private String attendeeCount;
	private String attendeeSeats;
	private String createdby;
	private String createtime;
	private String modifiedby;
	private String modifiedtime;

	public Eventregistration() {
	}

	public Eventregistration(int id, String eventid, String userid,
			String attendeeName, String attendeeAge, String attendeeDob,
			String attendeeCount, String attendeeSeats) {
		this.id = id;
		this.eventid = eventid;
		this.userid = userid;
		this.attendeeName = attendeeName;
		this.attendeeAge = attendeeAge;
		this.attendeeDob = attendeeDob;
		this.attendeeCount = attendeeCount;
		this.attendeeSeats = attendeeSeats;
	}

	public Eventregistration(int id, String eventid, String userid,
			String attendeeName, String attendeeAge, String attendeeDob,
			String attendeeCount, String attendeeSeats, String createdby,
			String createtime, String modifiedby, String modifiedtime) {
		this.id = id;
		this.eventid = eventid;
		this.userid = userid;
		this.attendeeName = attendeeName;
		this.attendeeAge = attendeeAge;
		this.attendeeDob = attendeeDob;
		this.attendeeCount = attendeeCount;
		this.attendeeSeats = attendeeSeats;
		this.createdby = createdby;
		this.createtime = createtime;
		this.modifiedby = modifiedby;
		this.modifiedtime = modifiedtime;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "eventid", nullable = false, length = 45)
	public String getEventid() {
		return this.eventid;
	}

	public void setEventid(String eventid) {
		this.eventid = eventid;
	}

	@Column(name = "userid", nullable = false, length = 45)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "attendee_name", nullable = false, length = 45)
	public String getAttendeeName() {
		return this.attendeeName;
	}

	public void setAttendeeName(String attendeeName) {
		this.attendeeName = attendeeName;
	}

	@Column(name = "attendee_age", nullable = false, length = 45)
	public String getAttendeeAge() {
		return this.attendeeAge;
	}

	public void setAttendeeAge(String attendeeAge) {
		this.attendeeAge = attendeeAge;
	}

	@Column(name = "attendee_dob", nullable = false, length = 45)
	public String getAttendeeDob() {
		return this.attendeeDob;
	}

	public void setAttendeeDob(String attendeeDob) {
		this.attendeeDob = attendeeDob;
	}

	@Column(name = "attendee_count", nullable = false, length = 45)
	public String getAttendeeCount() {
		return this.attendeeCount;
	}

	public void setAttendeeCount(String attendeeCount) {
		this.attendeeCount = attendeeCount;
	}

	@Column(name = "attendee_seats", nullable = false, length = 45)
	public String getAttendeeSeats() {
		return this.attendeeSeats;
	}

	public void setAttendeeSeats(String attendeeSeats) {
		this.attendeeSeats = attendeeSeats;
	}

	@Column(name = "createdby", length = 45)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "createtime", length = 45)
	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	@Column(name = "modifiedby", length = 45)
	public String getModifiedby() {
		return this.modifiedby;
	}

	public void setModifiedby(String modifiedby) {
		this.modifiedby = modifiedby;
	}

	@Column(name = "modifiedtime", length = 45)
	public String getModifiedtime() {
		return this.modifiedtime;
	}

	public void setModifiedtime(String modifiedtime) {
		this.modifiedtime = modifiedtime;
	}

}
